<div class="vehiclefitment-cnt">
    <div class="vehiclefitment-table">
        <div class="vehiclefitment-row heads">
            <div class="vehiclefitment-cell titles">
                <span>Year</span>
            </div>
            <div class="vehiclefitment-cell titles">
                <span>Make</span>
            </div>
            <div class="vehiclefitment-cell titles">
                <span>Model</span>
            </div>
            <div class="vehiclefitment-cell titles">
                <span>Sub model</span>
            </div>
            <div class="vehiclefitment-cell titles">
                <span>Bed length</span>
            </div>
            <div class="vehiclefitment-cell titles">
                <span>Wheel base</span>
            </div>
            <div class="vehiclefitment-cell titles">
                <span>Body door</span>
            </div>
            <div class="vehiclefitment-cell titles">
                <span>Body type</span>
            </div>
            <div class="vehiclefitment-cell titles">
                <span>Body type</span>
            </div>
        </div>
        <div class="vehiclefitment-row contents">
            <div class="vehiclefitment-cell cnt">
                <span>2020</span>
            </div>
            <div class="vehiclefitment-cell cnt">
                <span>Toyota</span>
            </div>
            <div class="vehiclefitment-cell cnt">
                <span>Pickup</span>
            </div>
            <div class="vehiclefitment-cell cnt">
                <span>DLX</span>
            </div>
            <div class="vehiclefitment-cell cnt">
                <span>--</span>
            </div>
            <div class="vehiclefitment-cell cnt">
                <span>--</span>
            </div>
            <div class="vehiclefitment-cell cnt">
                <span>--</span>
            </div>
            <div class="vehiclefitment-cell cnt">
                <span>Extended Cab Pickup</span>
            </div>
            <div class="vehiclefitment-cell cnt">
                <span>--</span>
            </div>
        </div>
        <div class="vehiclefitment-row contents">
            <div class="vehiclefitment-cell cnt">
                <span>2021</span>
            </div>
            <div class="vehiclefitment-cell cnt">
                <span>Toyota</span>
            </div>
            <div class="vehiclefitment-cell cnt">
                <span>Pickup</span>
            </div>
            <div class="vehiclefitment-cell cnt">
                <span>DLX</span>
            </div>
            <div class="vehiclefitment-cell cnt">
                <span>--</span>
            </div>
            <div class="vehiclefitment-cell cnt">
                <span>--</span>
            </div>
            <div class="vehiclefitment-cell cnt">
                <span>--</span>
            </div>
            <div class="vehiclefitment-cell cnt">
                <span>Extended Cab Pickup</span>
            </div>
            <div class="vehiclefitment-cell cnt">
                <span>--</span>
            </div>
        </div>     
    </div>
</div>