<?php
$tableAttributes = $block->getTableAttributes();
?>
<div class="vehiclefitment-cnt">
    <?php 
        if (empty($tableAttributes)) {
            echo __('No Fitment data available for this product');
        } 
        else 
        {
            foreach ($tableAttributes as $tableAttribute) { ?>
                <div class="vehiclefitment-table">
                    <div class="vehiclefitment-row heads">
                        <?php
                            $head = $block->getTableHead($tableAttribute['id']);
                            foreach ($head as $tableHead) { ?>
                                <div class="vehiclefitment-cell titles">
                                    <span><?= $tableHead['column_name'] ?></span>
                                </div>
                            <?php } ?>
                    </div>
                    <?php 
                    $rowCount = 0;
                    $values = (array) json_decode($tableAttribute['values']);
                    if (!empty($values)) { 
                        end($values);
                        $lastRow = key($values);
                        $totalRows = explode('-',$lastRow);
                        if (isset($totalRows[3])) {
                            $rowCount = $totalRows[3];
                        }
                        $currentRow = 0;
                        while ($currentRow < $totalRows[3]) {
                            $i = 0; ?>
                            <div class="vehiclefitment-row contents">
                                <?php 
                                foreach ($head as $tableHead) {
                                    $id = 'wkrow-'.$tableAttribute['id'].'-'.$tableHead['column_id'].'-'.($currentRow+1);
                                ?>
                                    <div class="vehiclefitment-cell cnt">
                                        <span>
                                            <?php if (isset($values[$id])) { ?>
                                                <?= $values[$id] ?>
                                            <?php } else { ?>
                                            <?php $i++; } ?> 
                                        </span>
                                    </div>
                                <?php } ?>
                            </div>
                            <?php $currentRow++;
                        }
                    } ?>
                </div>  
            <?php } 
        } ?>   
</div>