<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_Conf
 */
  use Magento\Framework\App\Action\Action;
?>

<?php /** @var \Amasty\Conf\Block\Product\View\Gallery $block */ ?>
<?php
$product_label='';
$_portohelper = $this->helper('Smartwave\Porto\Helper\Data');
$_product = $block->getProduct();
$prePurchaseData=$_portohelper->getPrepurchaseData($_product);

if(isset($prePurchaseData['is_pre_purchase']) && $prePurchaseData['is_pre_purchase']==1) {
    if($prePurchaseData['quantity_and_stock_status']=="" || $prePurchaseData['quantity_and_stock_status']==0){
        $now = date("Y-m-d");
        $prePurchaseFrom= substr($prePurchaseData['prepurchasestartdate'],0,10);
        $prePurchaseTo=  substr($prePurchaseData['prepurchaseenddate'],0,10);
        $releaseDate=  date('d-m-Y',strtotime(substr($prePurchaseData['release_date'],0,10)));
        if ($prePurchaseTo != '' || $prePurchaseFrom != ''){

        if (($prePurchaseTo != '' && $prePurchaseFrom != '' && $now>=$prePurchaseFrom && $now<=$prePurchaseTo) || ($prePurchaseTo == '' && $now >=$prePurchaseFrom) || ($prePurchaseFrom == '' && $now<=$prePurchaseTo)) {
                $product_label = 'Pre-Purchase';
        }
        }
    }
}
?>
<div class="gallery-placeholder" data-gallery-role="gallery-placeholder">
    <div id="amasty-gallery" data-role="amasty-gallery">
        <div class="gallery-placeholder _block-content-loading" data-gallery-role="gallery-loading">
            <div data-role="loader" class="loading-mask">
                <div class="loader">
                    <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')); ?>"
                         alt="<?= /* @noEscape */ __('Loading...') ?>">
                </div>
            </div>
        </div>
        <!--Fix for jumping content. Loader must be the same size as gallery.-->
        <script>
            var config = {
                    "width": <?= /* @noEscape */ $block->getImageAttribute('product_page_image_medium', 'width') ?>,
                    "thumbheight": <?= /* @noEscape */ $block->getImageAttribute('product_page_image_small', 'height')
                    ?: $block->getImageAttribute('product_page_image_small', 'width'); ?>,
                    "navtype": "<?= /* @noEscape */ $block->getVar("gallery/navtype") ?>",
                    "height": <?= /* @noEscape */ $block->getImageAttribute('product_page_image_medium', 'height') ?>
                },
                thumbBarHeight = 0,
                loader = document.querySelectorAll('[data-gallery-role="gallery-placeholder"] [data-role="loader"]')[0];

            if (config.navtype === 'horizontal') {
                thumbBarHeight = config.thumbheight;
            }

            loader.style.paddingBottom = ( config.height / config.width * 100) + "%";
        </script>

        <div id="amasty-main-container" data-gallery-role="amasty-main-container"></div>
        <?php if($product_label){ ?>
        <div class="product-labels" style="background-color: #2ba968;border-radius: 20px;color: #ffffff;height: 21px;
            font-size: 11px;
            line-height: 21px;
            padding: 0 10px"><?php echo $product_label; ?></div><br>
        <div class="product-labels" style="background-color: #2ba968;border-radius: 20px;color: #ffffff;height: 21px;
            font-size: 10px;
            line-height: 21px;
            padding: 0 8px">Launch At: <?php echo $releaseDate; ?></div>
        <?php } ?>
        <div id="amasty-gallery-container"  data-gallery-role="amasty-gallery-container">
            <div id="amasty-gallery-images"  data-gallery-role="amasty-gallery-images"></div>
        </div>

        <script type="text/x-magento-init">
        {
            "[data-role=amasty-gallery]": {
                "Amasty_Conf/js/amzoomer": {
                    "data": <?= /* @noEscape */ $block->getGalleryImagesJson() ?>,
                    "options":<?= /* @noEscape */ $block->getGalleryOptionJson() ?>
                }
            }
        }
        </script>
    </div>
</div>
