<?php
/**
 * Webkul Software
 *
 * @category  Webkul
 * @package   Webkul_ProductTableAttribute
 * @author    Webkul
 * @copyright Copyright (c) Webkul Software Private Limited (https://webkul.com)
 * @license   https://store.webkul.com/license.html
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Swatches\Block\Adminhtml\Attribute\Edit\Options\Text */

$stores = $block->getStoresSortedBySortOrder();
?>
<fieldset class="fieldset">
    <legend class="legend">
        <span><?= $block->escapeHtml(__('Manage Columns')) ?></span>
    </legend>
    <div id="table-columns-options-panel">
        <table class="data-table clearfix" cellspacing="0">
            <thead>
            <tr id="table-columns-options-table">

                <?php foreach ($stores as $_store): ?>
                    <th class="col-table col-<%- data.id %>
                        <?php if ($_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID): ?> _required<?php endif; ?>"
                    >
                        <span><?= $block->escapeHtml($_store->getName()) ?></span>
                    </th>
                <?php endforeach; ?>
                <th class="col-select"><span><?= $block->escapeHtml(__('Type')) ?></span></th>
                <?php $colTotal = count($stores) * 2 + 3; ?>
                <th class="col-delete">&nbsp;</th>
            </tr>
            </thead>
            <tbody data-role="table-columns-options-container" class="ignore-validate"></tbody>
            <tfoot>
            <tr>
                <th colspan="<?= (int)$colTotal ?>">
                    <input type="hidden" class="required-text-table-entry" name="text_table_validation"/>
                    <input type="hidden" class="required-text-table-unique" name="text_table_validation_unique"/>
                </th>
            </tr>
            <tr>
                <th colspan="<?= (int)$colTotal ?>" class="col-actions-add">
                    <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()):?>
                        <button id="add_new_table_text_option_button"
                                title="<?= $block->escapeHtml(__('Add Column')) ?>"
                                type="button" class="action- scalable add">
                            <span><?= $block->escapeHtml(__('Add Column')) ?></span>
                        </button>
                    <?php endif; ?>
                </th>
            </tr>
            </tfoot>
        </table>
        <input type="hidden" id="table-columns-option-count-check" value="" />
    </div>
    <script id="table-columns-row-template" type="text/x-magento-template">
        <tr>
            <?php foreach ($stores as $_store): ?>
                <?php $storeId = (int)$_store->getId(); ?>
                <td class="col-table col-<%- data.id %>">
                    <input class="input-text
                    table-columns-field-<?= /* @noEscape */ $storeId ?>
                        <?php if ($storeId == \Magento\Store\Model\Store::DEFAULT_STORE_ID): ?> required-option required-unique<?php endif; ?>"
                           name="tableColumnOption[value][<%- data.id %>][<?= /* @noEscape */ $storeId ?>]"
                           type="text" value="<%- data.table<?= /* @noEscape */ $storeId ?> %>"
                           placeholder="<?= $block->escapeHtml(__("Column Name")) ?>"/>
                </td>
            <?php endforeach; ?>
            <td id="delete_button_table_container_<%- data.id %>" class="col-delete">
                <input type="hidden" class="delete-flag" name="optiontext[delete][<%- data.id %>]" value="" />
                <?php if (!$block->getReadOnly() && !$block->canManageOptionDefaultOnly()):?>
                    <button title="<?= $block->escapeHtml(__('Delete')) ?>" type="button"
                            class="action- scalable delete delete-option">
                        <span><?= $block->escapeHtml(__('Delete')) ?></span>
                    </button>
                <?php endif;?>
            </td>
        </tr>
    </script>
    <script type="text/x-magento-init">
        {
            "*": {
                "Webkul_ProductTableAttribute/js/table": <?= /* @escapeNotVerified */ $block->getJsonConfig() ?>
            }
        }
    </script>
</fieldset>