<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Grouped product data template
 *
 * @var $block \Magento\Catalog\Block\Product\View\BaseImage
 * @var $block \Magento\GroupedProduct\Block\Product\View\Type\Grouped
 */
?>
<?php $block->setPreconfiguredValue(); ?>
<?php $_product = $block->getProduct(); ?>
<?php $_associatedProducts = $block->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>
<?php $priceHelper = $this->helper(\Magento\Framework\Pricing\Helper\Data::class); ?>
<div class="table-wrapper grouped products-detail-grouped">
    <table class="table data grouped" id="super-product-table">
        <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Grouped product items') ?></caption>
        <thead>
        <tr>
            <th colspan="2" class="col item" scope="col"><?php /* @escapeNotVerified */ echo __('Product Name') ?></th>
            <?php if ($_product->isSaleable()): ?>
                <th class="col qty" scope="col"><?php /* @escapeNotVerified */ echo __('Qty') ?></th>
                <th class="col qty" scope="col"></th>
            <?php endif; ?>
            <th class="col price" scope="col"><?php /* @escapeNotVerified */ echo __('Price') ?></th>
        </tr>
        </thead>

        <?php if ($_hasAssociatedProducts): 
            $finalPrice=0;
        ?>
        <?php foreach ($_associatedProducts as $_item): ?>
        <tbody>
            <tr>
                <td data-th="<?php echo $block->escapeHtml(__('Image')); ?>" class="col image">
                    <?php $productImage = $block->getImage($_item, 'product_base_image'); ?>
                    <img src="<?= $productImage->getImageUrl(); ?>" />
                </td>
                <td data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>" class="col item">
                    <strong class="product-item-name"><?php echo $block->escapeHtml($_item->getName()) ?></strong> 
                </td>
                <?php if ($_product->isSaleable()): ?>
                <td data-th="<?php echo $block->escapeHtml(__('Qty')); ?>" class="col qty">
                <?php if ($_item->isSaleable()) : ?>
                   <div class="product-qty-action"> 
                        <div class="product-actionqty"> 
                                <div class="control qty">
                                    <input type="number" name="super_group[<?php /* @escapeNotVerified */ echo $_item->getId() ?>]"
                                        maxlength="12"
                                        value="<?php /* @escapeNotVerified */ echo $_item->getQty() * 1 ?>"
                                        title="<?php /* @escapeNotVerified */ echo __('Qty') ?>"
                                        class="input-text qty"
                                        data-validate="{'validate-grouped-qty':'#super-product-table'}"
                                        data-errors-message-box="#validation-message-box"/>
                                    <div class="qty-changer">
                                        <a href="javascript:void(0)" class="qty-inc"><i class="porto-icon-up-dir"></i></a>
                                        <a href="javascript:void(0)" class="qty-dec"><i class="porto-icon-down-dir"></i></a>
                                    </div>
                                </div>
                        </div>  
                    </div>
                       
                <?php else: ?>
                    <div class="stock unavailable" title="<?php /* @escapeNotVerified */ echo __('Availability') ?>">
                        <span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span>
                    </div>
                <?php endif; ?>
                </td>
                <td>
                    <div class="product-actionwish">
                        <div class="moved-add-to-links"></div>
                    </div> 
                </td>               
                <?php endif; ?>
                <td class="col price">
                    <?php if ($block->getCanShowProductPrice($_product)): ?>
                        <?php if ($block->getCanShowProductPrice($_item)): ?>
                            <?php /* @escapeNotVerified */ echo $block->getProductPrice($_item) ?>
                            <?php $finalPrice +=$_item->getPrice(); ?>
                        <?php endif; ?>
                    <?php endif; ?>
                </td>
            </tr>
            <?php if ($block->getCanShowProductPrice($_product)
                && $block->getCanShowProductPrice($_item)
                && trim($block->getProductPriceHtml(
                    $_item,
                    \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                ))): ?>
                <tr class="row-tier-price">
                    <td colspan="2">
                        <?php echo $block->getProductPriceHtml(
                            $_item,
                            \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                        ) ?>
                    </td>
                </tr>
            <?php endif; ?>
        </tbody>
        <?php endforeach; ?>

        <?php else: ?>
        <tbody>
            <tr>
                <td class="unavailable"
                    colspan="<?php if ($_product->isSaleable()): ?>4<?php else : ?>3<?php endif; ?>">
                    <?php /* @escapeNotVerified */ echo __('No options of this product are available.') ?>
                </td>
            </tr>
        </tbody>
        <?php endif; ?>
        <tbody>
            <tr>
                <td colspan="4" align="right">
                    <div class="grouped_product_lable">
                        Total Price:
                    </div>          
                </td>
                <td>
                    <div class="grouped_product_price">
                        <div class="grouped_product_final_price">
                            <?= $formattedPrice = $priceHelper->currency($finalPrice, true, false); ?>
                        </div>        
                    </div>
                <td>
            </tr>
        </tbody>
    </table>
</div>
<div id="validation-message-box"></div>
