<div class="blk-advance">
    <div class="blk-advance-title">
        <span>Advance Search</span>
    </div>
    <div class="blk-advance-cnt">
        <div class="advance-cnt-sel">
            <select name="make" id="make">
                <option value="">Select Make</option>
            </select>
        </div>
        <div class="advance-cnt-sel">
            <select name="year" id="year">
                <option value="year">Select Year</option>
            </select>
        </div>
        <div class="advance-cnt-sel">
            <select name="model" id="model">
                <option value="">Select Model</option>
            </select>
        </div>
        <div class="advance-cnt-sel advance-cnt-btn">
            <button type="button">Search</button>
        </div>
    </div>
</div>