<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2020 Amasty (https://www.amasty.com)
 * @package Amasty_Stockstatus
 */

/** @var $block \Amasty\Stockstatus\Block\Adminhtml\Product\Edit\Ranges */
?>
<fieldset class="fieldset">
    <legend class="legend"><span><?= $block->escapeHtml(__('Manage Quantity Ranges')) ?></span></legend>
    <div id="manage-options-panel">
        <div class="box">
            <div class="hor-scroll1">
                <div style="clear: both"></div>
                <table cellpadding="5" cellspacing="8" id="ranges_table" class="admin__control-table" >
                    <thead>
                    <th><?= $block->escapeHtml(__('Quantity From')) ?></th>
                    <th><?= $block->escapeHtml(__('Quantity To')) ?></th>
                    <th><?= $block->escapeHtml(__('Custom Stock Status')) ?></th>
                    <?php if ($block->getHelper()->getRulesEnabled()): ?>
                        <th><?= $block->escapeHtml(__('Quantity Range Product Group')) ?></th>
                    <?php endif; ?>
                    <th><?= $block->escapeHtml(__('Remove')) ?></th>
                    </thead>
                    <tbody id="ranges_table_body"></tbody>
                </table>
                <br />
                <button class="add-new-range action- scalable add" title="<?= $block->escapeHtml(__('Add New Range Status')) ?>">
                    <span><?= $block->escapeHtml(__('Add New Range Status')) ?></span>
                </button>
            </div>
        </div>
    </div>
</fieldset>
<script>
    require([
        'jquery',
        'Amasty_Stockstatus/js/ranges'
    ], function($, amstockstatus) {
        $( window ).ready(function() {
            window.amstatuses = <?= /* @noEscape */ $block->getOptionValuesJson()?>;

            <?php if ($block->getHelper()->getRulesEnabled()): ?>
                window.amrules = <?= /* @noEscape */ $block->getRuleValuesJson()?>;
            <?php endif; ?>

            $('.add-new-range').click(function () {
                amstockstatus.addRange();
                return false;
            });
            $( "#ranges_table" ).on( "click", ".am-delete-range", function() {
                amstockstatus.removeCurrentRow(this);
            });

            <?php foreach ($block->getRanges() as $range): ?>
                amstockstatus.addRange(
                    <?= (int)($range->getData('entity_id'))  ?>,
                    <?= (int)($range->getData('qty_from')) ?>,
                    <?= (int)($range->getData('qty_to')) ?>,
                    <?= (int)($range->getData('status_id')) ?>
                    <?= $block->escapeJs(($range->getData('rule')) ? ',' . $range->getData('rule') : '') ?>
                );
            <?php endforeach; ?>
        });
    });
</script>
